// saliksik-client/src/pages/main/[researchID]/createConceptNote.svelte
<script lang="ts">
  import { Alert, Button, Card, FloatingLabelInput, Helper, Input, P, Textarea, Toolbar, ToolbarButton, ToolbarGroup } from "flowbite-svelte";
  import { CodeOutline, FaceGrinOutline, FileCirclePlusOutline, ImageOutline, MapPinAltSolid, PaperClipOutline, PapperPlaneOutline, QuestionCircleOutline, UserAddOutline } from "flowbite-svelte-icons";
  import { DateInput } from "date-picker-svelte";
  import { selectedResearchInfo, updateResearch } from "../../../components/store";
  import { goto } from "@roxi/routify";

  let data = { conceptNote: {} };

  function submit(e: Event) {
    e.preventDefault();
    const formData = new FormData(e.target as HTMLFormElement);
    let json = Object.fromEntries(formData.entries());
    data.conceptNote = {
      ...json,
      projectDuration,
    };

    fetch(`/api/research/updateResearch?researchID=${$selectedResearchInfo._id}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    })
      .then((response) => {
        if (response.ok) {
          //To edit
          $goto("/main/");
        } else {
          console.error("Login failed");
        }
      })
      .catch((error) => {
        console.error("Network error:", error);
      });
  }

  //for pop-up admin-buttons
  let saveAsDraft = false;
  let submitResearchProposal = false;

  //date picker
  let projectDuration = new Date();
</script>

<main class="p-4">
  <div class="flex justify-center gap-2 mb-10">
    <div class="grid grid-flow-row col-start-2 col-span-3 items-center gap-2 w-1/2 sm:w-full md:w-full lg:w-11/12 xl:w-8/12 2xl:w-3/4">

      <form on:submit={submit} class="flex flex-wrap justify-start items-center gap-2 w-full">
        <div class="flex flex-wrap justify-start items-center w-full mb-2">
          <div class="flex justify-between items-center w-full">
            <div class="flex items-center gap-2">
              <FileCirclePlusOutline size="md" class="text-blue-700" />
              <P size="xl" weight="bold" class="text-gray-900">Create Concept Note</P>
            </div>
            <div class="flex items-center gap-2">
              <Button color="blue" size="sm" class="flex items-center gap-2 rounded-md"><UserAddOutline size="sm" />Save as Draft</Button>
              <Button type="submit" outline color="blue" size="sm" class="flex items-center gap-2 rounded-md"><UserAddOutline size="sm" />Submit</Button>
            </div>
          </div>
          <P size="sm" weight="normal" class="text-gray-500">Fill out all empty fields with the appropriate texts. Put "N/A" if not applicable and "To Be Followed" as it states.</P>
        </div>

        <div class="grid grid-flow-row items-center gap-2 shadow-lg border rounded-md p-3 mb-4 w-full bg-white">
          <div class="flex flex-wrap items-center gap-1">
            <P weight="medium" size="base">Implementing Agency/Department</P>
            <Input type="text" size="sm" id="implementingDept" name="implementingDept" label="Implementing Agency/Department" required class="rounded-md text-gray-500"></Input>
            <Helper class=" text-gray-500"></Helper>
          </div>
          <div class="flex flex-wrap items-center gap-1">
            <P weight="medium" size="base">Cooperating Agency</P>
            <Input type="text" size="sm" id="coopAgency" name="coopAgency" label="Cooperating Agency" required class="rounded-md text-gray-500"></Input>
            <Helper class=" text-gray-500">State the name of agency to be tapped for funding/ co-implementing the project.</Helper>
          </div>
          <div class="flex flex-wrap items-center gap-1">
            <P weight="medium" size="base">Site/s of Implementation</P>
            <Input type="text" size="sm" id="siteImplementation" name="siteImplementation" label="Site/s of Implementation" required class="rounded-md text-gray-500"></Input>
            <Helper class=" text-gray-500">Site/s of Implementation</Helper>
          </div>
          <div class="flex flex-wrap items-center gap-1">
            <P weight="medium" size="base">Total Project Cost</P>
            <Input type="text" size="sm" id="totalCost" name="totalCost" label="Total Project Cost" required class="rounded-md text-gray-500"></Input>
            <Helper class=" text-gray-500">Include the specific budget allocations for personnel service, maintenance and operations, equipment, trainings/workshops, and administrative costs.</Helper>
          </div>
          <div class="flex flex-wrap items-center gap-1">
            <P weight="medium" size="base">Funding Source</P>
            <Input type="text" size="sm" id="fundingSource" name="fundingSource" label="Funding Source" required class="rounded-md text-gray-500"></Input>
            <Helper class=" text-gray-500">Specific funding source, including counterpart funds.</Helper>
          </div>

          <div class="flex flex-wrap items-center gap-1">
            <P weight="medium" size="base" for="researchLeaders">Project Duration</P>
            <DateInput bind:value={projectDuration} format="yyyy-MM-dd" placeholder="yyyy-MM-dd" required --date-picker-highlight-border="#b43403" --date-picker-highlight-shadow="none" --date-input-width="100%" class="w-full rounded-md text-gray-500" />
            <Helper class=" text-gray-500">Specific dates that the project will be undertaken (month/year); ideally to be completed minimum 1 year/ depending on the approved grant.</Helper>
          </div>
        </div>

        <!--project description-->
        <div class="grid grid-flow-row items-center gap-1 shadow-lg border rounded-md p-3 mb-4 w-full bg-white">
          <P weight="semibold" size="lg">Project Description</P>
          <Textarea id="description" name="description" rows="15" class="mb-0 p-0">
            <Toolbar slot="header" embedded class="m-0 p-0">
              <ToolbarGroup>
                <ToolbarButton name="Attach file"><PaperClipOutline size="sm" /></ToolbarButton>
                <ToolbarButton name="Embed map"><MapPinAltSolid size="sm" /></ToolbarButton>
                <ToolbarButton name="Upload image"><ImageOutline size="sm" /></ToolbarButton>
              </ToolbarGroup>
              <ToolbarGroup>
                <ToolbarButton name="Format code"><CodeOutline size="sm" /></ToolbarButton>
                <ToolbarButton name="Add emoji"><FaceGrinOutline size="sm" /></ToolbarButton>
              </ToolbarGroup>
              
            </Toolbar>
          </Textarea>
          <Helper class=" text-gray-500">Formally written declaration of the project and its idea and context to explain the goals and objectives to be reached and other relevant information that explains the need for the project and aims to describe the amount of work planned for implementation; refers to a simple explanation or depiction of the project that can be used as communication material.</Helper>
        </div>

        <!--significance-->
        <div class="grid grid-flow-row items-center gap-1 shadow-lg border rounded-md p-3 mb-4 w-full bg-white">
          <P weight="semibold" size="xl">Significance</P>
          <Textarea id="significance" name="significance" rows="15" class="mb-0 p-0">
            <Toolbar slot="header" embedded class="m-0 p-0">
              <ToolbarGroup>
                <ToolbarButton name="Attach file"><PaperClipOutline size="sm" /></ToolbarButton>
                <ToolbarButton name="Embed map"><MapPinAltSolid size="sm" /></ToolbarButton>
                <ToolbarButton name="Upload image"><ImageOutline size="sm" /></ToolbarButton>
              </ToolbarGroup>
              <ToolbarGroup>
                <ToolbarButton name="Format code"><CodeOutline size="sm" /></ToolbarButton>
                <ToolbarButton name="Add emoji"><FaceGrinOutline size="sm" /></ToolbarButton>
              </ToolbarGroup>
              
            </Toolbar>
          </Textarea>
          <Helper class=" text-gray-500">Refers to the alignment to UNC research agenda/ UN SDG / tapped agency provided in the matrix attached; review of literature may refer to the following: (a) related researches that have been conducted, state-of-the-art or current technologies from which the project will take off; (b) scientific/technical merit; (c) results of related research conducted by the same Project Leader, if any; (d) Prior Art Search, and; (e) other relevant.</Helper>
        </div>

        <!--objectives-->
        <div class="grid grid-flow-row items-center gap-1 shadow-lg border rounded-md p-3 mb-4 w-full bg-white">
          <P weight="semibold" size="lg">Objectives</P>
          <Textarea id="objectives" name="objectives" rows="15" class="mb-0 p-0">
            <Toolbar slot="header" embedded class="m-0 p-0">
              <ToolbarGroup>
                <ToolbarButton name="Attach file"><PaperClipOutline size="sm" /></ToolbarButton>
                <ToolbarButton name="Embed map"><MapPinAltSolid size="sm" /></ToolbarButton>
                <ToolbarButton name="Upload image"><ImageOutline size="sm" /></ToolbarButton>
              </ToolbarGroup>
              <ToolbarGroup>
                <ToolbarButton name="Format code"><CodeOutline size="sm" /></ToolbarButton>
                <ToolbarButton name="Add emoji"><FaceGrinOutline size="sm" /></ToolbarButton>
              </ToolbarGroup>
              
            </Toolbar>
          </Textarea>
          <Helper class=" text-gray-500">Statements of the general and specific purposes to address the problem areas of the project; must anchor to the UNC agenda/ SDG/ grant giving body’s agenda.</Helper>
        </div>

        <!--methodology-->
        <div class="grid grid-flow-row items-center gap-1 shadow-lg border rounded-md p-3 mb-4 w-full bg-white">
          <P weight="semibold" size="lg">Methodology</P>
          <Textarea id="methodology" name="methodology" rows="15" class="mb-0 p-0">
            <Toolbar slot="header" embedded class="m-0 p-0">
              <ToolbarGroup>
                <ToolbarButton name="Attach file"><PaperClipOutline size="sm" /></ToolbarButton>
                <ToolbarButton name="Embed map"><MapPinAltSolid size="sm" /></ToolbarButton>
                <ToolbarButton name="Upload image"><ImageOutline size="sm" /></ToolbarButton>
              </ToolbarGroup>
              <ToolbarGroup>
                <ToolbarButton name="Format code"><CodeOutline size="sm" /></ToolbarButton>
                <ToolbarButton name="Add emoji"><FaceGrinOutline size="sm" /></ToolbarButton>
              </ToolbarGroup>
              
            </Toolbar>
          </Textarea>
          <Helper class=" text-gray-500">Discuss the following: (a) variables or parameters to be measured and evaluated or analyzed; (b) treatments to be used and their layout; (c) experimental procedures and design; (d) statistical analysis; (e) evaluation method and observations to be made, strategies for implementation (Conceptual/Analytical framework).</Helper>
        </div>

        <!--technology roadmap-->
        <div class="grid grid-flow-row items-center gap-1 shadow-lg border rounded-md p-3 mb-4 w-full bg-white">
          <P weight="semibold" size="lg">Technology Roadmap</P>
          <Textarea id="technologyRoadmap" name="technologyRoadmap" rows="15" class="mb-0 p-0">
            <Toolbar slot="header" embedded class="m-0 p-0">
              <ToolbarGroup>
                <ToolbarButton name="Attach file"><PaperClipOutline size="sm" /></ToolbarButton>
                <ToolbarButton name="Embed map"><MapPinAltSolid size="sm" /></ToolbarButton>
                <ToolbarButton name="Upload image"><ImageOutline size="sm" /></ToolbarButton>
              </ToolbarGroup>
              <ToolbarGroup>
                <ToolbarButton name="Format code"><CodeOutline size="sm" /></ToolbarButton>
                <ToolbarButton name="Add emoji"><FaceGrinOutline size="sm" /></ToolbarButton>
              </ToolbarGroup>
              
            </Toolbar>
          </Textarea>
          <Helper class=" text-gray-500">(if applicable) A visual document that communicates the plan for technology.</Helper>
        </div>

        <!--expected outputs-->
        <div class="grid grid-flow-row items-center gap-1 shadow-lg border rounded-md p-3 mb-4 w-full bg-white">
          <P weight="semibold" size="lg">Expected Outputs (6Ps)</P>
          <Textarea id="expectedOutput" name="expectedOutput" rows="15" class="mb-0 p-0">
            <Toolbar slot="header" embedded class="m-0 p-0">
              <ToolbarGroup>
                <ToolbarButton name="Attach file"><PaperClipOutline size="sm" /></ToolbarButton>
                <ToolbarButton name="Embed map"><MapPinAltSolid size="sm" /></ToolbarButton>
                <ToolbarButton name="Upload image"><ImageOutline size="sm" /></ToolbarButton>
              </ToolbarGroup>
              <ToolbarGroup>
                <ToolbarButton name="Format code"><CodeOutline size="sm" /></ToolbarButton>
                <ToolbarButton name="Add emoji"><FaceGrinOutline size="sm" /></ToolbarButton>
              </ToolbarGroup>
              
            </Toolbar>
          </Textarea>
          <Helper class=" text-gray-500">Deliverables of the project based on the 6Ps metrics of DOST/ typical grants suggested deliverables (Publication, Patent/Intellectual Property, Product, People Service, Place and Partnership, and Policy).</Helper>
        </div>

        <!--work plan-->
        <div class="grid grid-flow-row items-center gap-1 shadow-lg border rounded-md p-3 mb-4 w-full bg-white">
          <P weight="semibold" size="lg">Work Plan</P>
          <Textarea id="workPlan" name="workPlan" rows="15" class="mb-0 p-0">
            <Toolbar slot="header" embedded class="m-0 p-0">
              <ToolbarGroup>
                <ToolbarButton name="Attach file"><PaperClipOutline size="sm" /></ToolbarButton>
                <ToolbarButton name="Embed map"><MapPinAltSolid size="sm" /></ToolbarButton>
                <ToolbarButton name="Upload image"><ImageOutline size="sm" /></ToolbarButton>
              </ToolbarGroup>
              <ToolbarGroup>
                <ToolbarButton name="Format code"><CodeOutline size="sm" /></ToolbarButton>
                <ToolbarButton name="Add emoji"><FaceGrinOutline size="sm" /></ToolbarButton>
              </ToolbarGroup>
              
            </Toolbar>
          </Textarea>
          <Helper class=" text-gray-500">Specific activity to be undertaken per month in a gantt chart to produce the promised results to attain the objectives of the project.</Helper>
        </div>
      </form>
    </div>
  </div>

  <div class="h-96"></div>
</main>

// client/src/pages/researcher/[research_id.vue]/create_concept_note.vue
<template>
  <v-container fluid class="fill-height ctr">
    <!--header-->
    <v-form class="form-concept-note" @submit.prevent="create">
      <v-card flat class="body">
        <v-card-title class="header">
          <div class="header-left">
            <div class="header-caption">
                <h5 style="">Create Concept Note</h5>

              <p class="help" style="margin-top: .2rem;" >
                help
                <v-tooltip activator="parent" location="bottom">Fill out all required fields. Put "N/A" if not
                  applicable. </v-tooltip>
              </p>
            </div>
          </div>

          <div class="header-right">
            <v-btn variant="tonal" prepend-icon="mdi-file-document-check-outline" type="submit" text="Submit"
              class="button-regular" />
          </div>
        </v-card-title>

        <v-card-text class="card-ctr-concept-note">
          <!--form-->

          <v-card class="card-concept-note" variant="flat" >
            <v-textarea v-model="projectTitle.value.value" :error-messages="projectTitle.errorMessage.value"
              label="Project Title" density="compact" required rows="1" auto-grow variant="outlined" color="#5b21b6"
              style="color: #5b21b6" />
            <v-row>
              <v-col class="card-concept-note">
                <v-textarea v-model="implementingAgency.value.value"
                  :error-messages="implementingAgency.errorMessage.value" label="Implementing Agency/Department"
                  density="compact" rows="1" auto-grow required variant="outlined" color="#5b21b6"
                  style="color: #5b21b6" />
                <v-textarea v-model="cooperatingAgency.value.value"
                  :error-messages="cooperatingAgency.errorMessage.value" label="Cooperating Agency" density="compact"
                  rows="1" auto-grow required variant="outlined" color="#5b21b6" style="color: #5b21b6">
                  <v-tooltip activator="parent" location="top">
                    State the name of agency to be tapped for funding/
                    co-implementing the project.
                  </v-tooltip>
                </v-textarea>
                <v-textarea v-model="siteOfImplementation.value.value"
                  :error-messages="siteOfImplementation.errorMessage.value" label="Site/s of Implementation"
                  density="compact" rows="1" auto-grow required variant="outlined" color="#5b21b6"
                  style="color: #5b21b6" />
              </v-col>
              <v-col class="card-concept-note">
                <v-text-field v-model="projectDuration.value.value" :error-messages="projectDuration.errorMessage.value"
                  label="Project Duration" density="compact" required variant="outlined" color="#5b21b6"
                  style="color: #5b21b6">
                  <v-tooltip activator="parent" location="top" width="30%">Specific dates that the project will be
                    undertaken
                    (month/year); ideally to be completed minimum 1 year/
                    depending on the approved grant.</v-tooltip>
                </v-text-field>
                <v-text-field v-model="totalProjectCost.value.value"
                  :error-messages="totalProjectCost.errorMessage.value" label="Total Project Cost" density="compact"
                  required variant="outlined" color="#5b21b6" style="color: #5b21b6">
                  <v-tooltip activator="parent" location="top" width="30%">
                    Include the specific budget allocations for personnel
                    service, maintenance and operations, equipment,
                    trainings/workshops, and administrative costs.</v-tooltip>
                </v-text-field>
                <v-text-field v-model="fundingSource.value.value" :error-messages="fundingSource.errorMessage.value"
                  label="Funding Source" density="compact" required variant="outlined" color="#5b21b6"
                  style="color: #5b21b6">
                  <v-tooltip activator="parent" location="top">
                    Specific funding source, including counterpart funds.
                  </v-tooltip>
                </v-text-field>
              </v-col>
            </v-row>
          </v-card>
          <v-card class="card-concept-note2" variant="flat" >
            <v-textarea v-model="projectDescription.value.value" :error-messages="projectDescription.errorMessage.value"
              label="Project Description" variant="outlined" required auto-grow color="#5b21b6"
              style="color: #5b21b6" />
            <v-tooltip activator="parent" location="top" width="75%">
              Formally written declaration of the project and its idea and
              context to explain the goals and objectives to be reached and
              other relevant information that explains the need for the project
              and aims to describe the amount of work planned for
              implementation; refers to a simple explanation or depiction of the
              project that can be used as communication material.
            </v-tooltip>
            <v-file-input label="Upload images, charts, tables here, if necessary." variant="outlined" required chips
              multiple color="#5b21b6" style="color: #5b21b6" />
          </v-card>
          <v-card class="card-concept-note2" variant="flat" >
            <v-textarea v-model="significance.value.value" :error-messages="significance.errorMessage.value"
              label="Significance" variant="outlined" required auto-grow color="#5b21b6" style="color: #5b21b6" />
            <v-tooltip activator="parent" location="top" width="75%">Refers to the alignment to UNC research agenda/ UN
              SDG / tapped
              agency provided in the matrix attached; review of literature may
              refer to the following: (a) related researches that have been
              conducted, state-of-the-art or current technologies from which the
              project will take off; (b) scientific/technical merit; (c) results
              of related research conducted by the same Project Leader, if any;
              (d) Prior Art Search, and; (e) other relevant.
            </v-tooltip>
            <v-file-input label="Upload images, charts, tables here, if necessary." variant="outlined" required chips
              multiple color="#5b21b6" style="color: #5b21b6" />
          </v-card>
          <v-card class="card-concept-note2" variant="flat" >
            <v-textarea v-model="objectives.value.value" :error-messages="objectives.errorMessage.value"
              label="Objectives" variant="outlined" required auto-grow color="#5b21b6" style="color: #5b21b6" />
            <v-tooltip activator="parent" location="top" width="75%">Statements of the general and specific purposes to
              address the
              problem areas of the project; must anchor to the UNC agenda/ SDG/
              grant giving body’s agenda.
            </v-tooltip>
            <v-file-input label="Upload images, charts, tables here, if necessary." variant="outlined" required chips
              multiple color="#5b21b6" style="color: #5b21b6" />
          </v-card>
          <v-card class="card-concept-note2" variant="flat" >
            <v-textarea v-model="methodology.value.value" :error-messages="methodology.errorMessage.value"
              label="Methodology" variant="outlined" required auto-grow color="#5b21b6" style="color: #5b21b6" />
            <v-tooltip activator="parent" location="top" width="75%">Discuss the following: (a) variables or parameters
              to be measured
              and evaluated or analyzed; (b) treatments to be used and their
              layout; (c) experimental procedures and design; (d) statistical
              analysis; (e) evaluation method and observations to be made,
              strategies for implementation (Conceptual/Analytical framework).
            </v-tooltip>
            <v-file-input label="Upload images, charts, tables here, if necessary." variant="outlined" required chips
              multiple color="#5b21b6" style="color: #5b21b6" />
          </v-card>
          <v-card class="card-concept-note2" variant="flat" >
            <v-textarea v-model="technologyRoadmap.value.value" :error-messages="technologyRoadmap.errorMessage.value"
              label="Technology Roadmap" variant="outlined" required auto-grow color="#5b21b6" style="color: #5b21b6" />
            <v-tooltip activator="parent" location="top" width="25%">
              (If applicable) A visual document that communicates the plan for
              technology.
            </v-tooltip>
            <v-file-input label="Upload images, charts, tables here, if necessary." variant="outlined" required chips
              multiple color="#5b21b6" style="color: #5b21b6" />
          </v-card>
          <v-card class="card-concept-note2" variant="flat" >
            <v-textarea v-model="expectedOutputs.value.value" :error-messages="expectedOutputs.errorMessage.value"
              label="Expected Outputs (6Ps)" variant="outlined" required auto-grow color="#5b21b6"
              style="color: #5b21b6" />
            <v-tooltip activator="parent" location="top" width="75%">Deliverables of the project based on the 6Ps
              metrics of DOST/
              typical grants suggested deliverables (Publication,
              Patent/Intellectual Property, Product, People Service, Place and
              Partnership, and Policy).
            </v-tooltip>
            <v-file-input label="Upload images, charts, tables here, if necessary." variant="outlined" required chips
              multiple color="#5b21b6" style="color: #5b21b6" />
          </v-card>
          <v-card class="card-concept-note2" variant="flat" >
            <v-textarea v-model="workPlan.value.value" :error-messages="workPlan.errorMessage.value" label="Work Plan"
              variant="outlined" required auto-grow color="#5b21b6" style="color: #5b21b6" />
            <v-tooltip activator="parent" location="top" width="25%">Detailed plan of activities and timeline for the
              project</v-tooltip>
            <v-file-input label="Upload images, charts, tables here, if necessary." variant="outlined" required chips
              multiple color="#5b21b6" style="color: #5b21b6" />
          </v-card>
        </v-card-text>
      </v-card>
    </v-form>
  </v-container>
</template>

<script setup lang="ts">
import router from "@/router";
import { useResearchesStore } from "@/stores/researches";
import axios from "axios";
import { useField, useForm } from "vee-validate";
const r = useResearchesStore();
const research = r.currentResearch;

const { handleSubmit } = useForm({
  validationSchema: {
    projectTitle: (v: string) => (v ? true : "Field is required."),
    implementingAgency: (v: string) => (v ? true : "Field is required."),
    cooperatingAgency: (v: string) => (v ? true : "Field is required."),
    siteOfImplementation: (v: string) => (v ? true : "Field is required."),
    projectDuration: (v: string) => (v ? true : "Field is required."),
    totalProjectCost: (v: string) =>
      !isNaN(Number(v)) ? true : "Field must be a number.",
    fundingSource: (v: string) => (v ? true : "Field is required."),
    projectDescription: (v: string) => (v ? true : "Field is required."),
    significance: (v: string) => (v ? true : "Field is required."),
    objectives: (v: string) => (v ? true : "Field is required."),
    methodology: (v: string) => (v ? true : "Field is required."),
    technologyRoadmap: (v: string) => (v ? true : "Field is required."),
    expectedOutputs: (v: string) => (v ? true : "Field is required."),
    workPlan: (v: string) => (v ? true : "Field is required."),
  },
});

const projectTitle = useField("projectTitle");
const implementingAgency = useField("implementingAgency");
const cooperatingAgency = useField("cooperatingAgency");
const siteOfImplementation = useField("siteOfImplementation");
const projectDuration = useField("projectDuration");
const totalProjectCost = useField("totalProjectCost");
const fundingSource = useField("fundingSource");
const projectDescription = useField("projectDescription");
const significance = useField("significance");
const objectives = useField("objectives");
const methodology = useField("methodology");
const technologyRoadmap = useField("technologyRoadmap");
const expectedOutputs = useField("expectedOutputs");
const workPlan = useField("workPlan");

const create = handleSubmit(async (values) => {
  const data = JSON.stringify({
    researchStatus: "Concept Note",
    conceptNote: {
      ...values,
      status: 'Submitted',
    },
  });
  return axios
    // @ts-ignore
    .patch(`/api/research/update/${research._id}`, data, {
      headers: {
        "Content-Type": "application/json",
      },
    })
    .then(() => alert("Successfully created a new concept note"))
    .catch(() => alert("An error occurred"))
    .finally(() => router.push("/researcher/research_projects"));
});
</script>
